name: Run Tests

on:
  pull_request:

jobs:
  run-tests-postgres:
    name: Run Tests (Postgres ${{ matrix.postgres-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres-version: [14, 15, 16, 17, 18]
    permissions:
      contents: read
      pull-requests: write
    env:
      DATASOURCE_DB_USERNAME: postgres
      DATASOURCE_DB_PASSWORD: postgres
      DATASOURCE_DB_DATABASE: hutch-omop
      DATASOURCE_DB_SCHEMA: public
      DATASOURCE_DB_PORT: 5432
      DATASOURCE_DB_HOST: localhost
      TASK_API_TYPE: a
      COLLECTION_ID: test_collection
      TASK_API_BASE_URL: http://localhost:8000
      TASK_API_USERNAME: test_user
      TASK_API_PASSWORD: test_password
      TASK_API_ENFORCE_HTTPS: false
      OMOP_SPECIMEN_ENABLED: TRUE


    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hutch-omop
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v7

      - name: Load synthetic OMOP data
        run: |
          docker run \
            --network host \
            -e DB_HOST=localhost \
            -e DB_NAME=hutch-omop \
            -e DB_PASSWORD=postgres \
            -e DIALECT=postgresql \
            -e SYNTHETIC=true \
            -e SYNTHETIC_NUMBER=1001 \
            ghcr.io/health-informatics-uon/omop-lite:0.7.0

      - name: Setup uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.12.0"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: ".python-version"

      - name: uv sync
        run: uv sync --frozen --dev

      - name: Run tests
        run: |
          set -e
          uv run pytest -s tests --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=hutch_bunny tests | tee pytest-coverage.txt
          test ${PIPESTATUS[0]} -eq 0

      - name: Pytest coverage comment
        # Forks do not have the necessary permission to add a comment.
        if: github.event.pull_request.head.repo.fork == false
        uses: MishaKav/pytest-coverage-comment@ce64cfb4332195faa36733a0364dda8849109f70
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
  
  run-tests-sqlserver:
    name: Run Tests (SQL Server ${{ matrix.sqlserver-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sqlserver-version: [2019, 2022]
    permissions:
      contents: read
      pull-requests: write
    env:
      DATASOURCE_DB_USERNAME: sa
      DATASOURCE_DB_PASSWORD: Password123!
      DATASOURCE_DB_DATABASE: master
      DATASOURCE_DB_SCHEMA: omop
      DATASOURCE_DB_PORT: 1433
      DATASOURCE_DB_HOST: localhost
      DATASOURCE_DB_DRIVERNAME: mssql
      TASK_API_TYPE: a
      COLLECTION_ID: test_collection
      TASK_API_BASE_URL: http://localhost:8000
      TASK_API_USERNAME: test_user
      TASK_API_PASSWORD: test_password
      TASK_API_ENFORCE_HTTPS: false
      OMOP_SPECIMEN_ENABLED: TRUE


    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:${{ matrix.sqlserver-version }}-latest
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: Password123!
          MSSQL_PID: Developer
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v7

      - name: Load synthetic OMOP data
        run: |
          docker run \
            --network host \
            -e DB_HOST=localhost \
            -e DB_NAME=master \
            -e DB_USER=sa \
            -e DB_PASSWORD=Password123! \
            -e DB_PORT=1433 \
            -e DIALECT=mssql \
            -e SCHEMA_NAME=omop \
            -e SYNTHETIC=true \
            -e SYNTHETIC_NUMBER=1001 \
            ghcr.io/health-informatics-uon/omop-lite:0.7.0

      - name: Setup uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.12.0"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: ".python-version"

      - name: uv sync
        run: uv sync --frozen --dev

      - name: Run tests
        run: |
          set -e
          uv run pytest tests
